### ISSUE TITLE
WARN: Running the contributed command:'extension.blockalign' failed.

### ISSUE THREAD

**Issue by hilyin** [crewone/vscode-blockalign#1]
Just installed this extension and attempting to use it. I just get the error `WARN: Running the contributed command:'extension.blockalign' failed.`

Any help is appreciated. Thank you.

**Comment by phaberest** [comment]
Same issue here, did anyone manage how to solve this?

**Comment by crewone** [comment]
I have just moved so I'm a bit busy reorganizing boxes. But I will look at it in the near future!

**Comment by crewone** [comment]
Seems like the internals of VSCode have re-aligned with this extension again.

**Comment by luidyvcc** [comment]
I am using VS version 1.26.1, the problem remains.
